service: node-api-with-s3-layer

frameworkVersion: '^4.0.0'

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1

package:
  individually: true

layers:
  s3lib:
    path: layers/s3lib
    name: s3lib
    compatibleRuntimes:
      - nodejs22.x 

functions:
  create:
    handler: functions/create/handler.handler
    events:
      - http:
          path: items
          method: post
    layers:
      - { Ref: S3libLambdaLayer }

  read:
    handler: functions/read/handler.handler
    events:
      - http:
          path: items
          method: get
    layers:
      - { Ref: S3libLambdaLayer }

  update:
    handler: functions/update/handler.handler
    events:
      - http:
          path: items/{id}
          method: put
    layers:
      - { Ref: S3libLambdaLayer }

  delete:
    handler: functions/delete/handler.handler
    events:
      - http:
          path: items/{id}
          method: delete
    layers:
      - { Ref: S3libLambdaLayer }
